# Generated by Django 5.1.6 on 2025-02-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('queixa', models.CharField(choices=[('TD', 'TDAH'), ('DE', 'Depressão'), ('AN', 'Ansiedade'), ('AG', 'Transtorno de Ansiedade Generalizada')], default='TD', max_length=2)),
                ('foto', models.ImageField(upload_to='fotos')),
                ('inadimplente', models.BooleanField(default=False)),
            ],
        ),
    ]
